// Mocks generated by Mockito 5.4.6 from annotations
// in tdd_clean_archetecture/test/fetures/data/repositories/number_trivia_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_clean_archetecture/core/Network/network_info.dart' as _i6;
import 'package:tdd_clean_archetecture/feature/product_trivia/data/datasources/number_trivia_loacal_dataSource.dart'
    as _i5;
import 'package:tdd_clean_archetecture/feature/product_trivia/data/datasources/number_trivia_remote_datasource.dart'
    as _i3;
import 'package:tdd_clean_archetecture/feature/product_trivia/data/models/number_trivia_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNumberTriviaModel_0 extends _i1.SmartFake
    implements _i2.NumberTriviaModel {
  _FakeNumberTriviaModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NumberTriviaRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumberTriviaRemoteDatasource extends _i1.Mock
    implements _i3.NumberTriviaRemoteDatasource {
  MockNumberTriviaRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NumberTriviaModel> getRandomnumberTrivia() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomnumberTrivia, []),
            returnValue: _i4.Future<_i2.NumberTriviaModel>.value(
              _FakeNumberTriviaModel_0(
                this,
                Invocation.method(#getRandomnumberTrivia, []),
              ),
            ),
          )
          as _i4.Future<_i2.NumberTriviaModel>);

  @override
  _i4.Future<_i2.NumberTriviaModel> getConcritNumberTrivia(int? number) =>
      (super.noSuchMethod(
            Invocation.method(#getConcritNumberTrivia, [number]),
            returnValue: _i4.Future<_i2.NumberTriviaModel>.value(
              _FakeNumberTriviaModel_0(
                this,
                Invocation.method(#getConcritNumberTrivia, [number]),
              ),
            ),
          )
          as _i4.Future<_i2.NumberTriviaModel>);
}

/// A class which mocks [NumberTriviaLoacalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumberTriviaLoacalDatasource extends _i1.Mock
    implements _i5.NumberTriviaLoacalDatasource {
  MockNumberTriviaLoacalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NumberTriviaModel> getLastNumberTrivia() =>
      (super.noSuchMethod(
            Invocation.method(#getLastNumberTrivia, []),
            returnValue: _i4.Future<_i2.NumberTriviaModel>.value(
              _FakeNumberTriviaModel_0(
                this,
                Invocation.method(#getLastNumberTrivia, []),
              ),
            ),
          )
          as _i4.Future<_i2.NumberTriviaModel>);

  @override
  _i4.Future<void> cacheNumberTrivia(_i2.NumberTriviaModel? triviatoCache) =>
      (super.noSuchMethod(
            Invocation.method(#cacheNumberTrivia, [triviatoCache]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
